### ISSUE TITLE
Regular DB

### ISSUE THREAD

**Issue by MagnificentS** [kafagy95/fifa18-Data#5]
Hi i was wondering if you could include the regular Fifa DB

**Comment by kafagy** [comment]
Hi @MagnificentS,

Can you elaborate more on what you mean when you say "regular Fifa DB"?
Do you mean just a MySQL DB backup of the results I saved?

**Comment by MagnificentS** [comment]
FUT is different from the full database with player stats

**Comment by kafagy** [comment]
My main goal was just to have the main FUT stats, but I might consider doing the full DB player stats before the game release.

**Comment by kafagy** [comment]
its added in the FutBin19.csv
